//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int id { get; set; }
        public string NameOfCar { get; set; }
        public string ClassOfCar { get; set; }
        public string Description { get; set; }
        public string MainPhoto { get; set; }
        public string OtherPhotoes { get; set; }
        public int Count { get; set; }
        public int Price { get; set; }
    }
}
